name: Generate Snake1

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: VedantShirgaonkar
          outputs: |
            dist/github-contribution-grid-snake1.svg
          color_snake: "#39FF14"
          color_dots: "#161B22,#0D1117,#30363D,#58A6FF"

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
